name: Rust

on:
  push:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libs
      run: sudo apt install librust-alsa-sys-dev libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Run tests
      run: cargo test --verbose

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install libs
      run: sudo apt install librust-alsa-sys-dev
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Release Build
      run: cargo build --release
    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: release
        path: target/release/voida
        retention-days: 2